'use server';
/**
 * @fileOverview A Genkit flow to generate audio from text using Google's TTS model.
 *
 * - generateAudio - A function that handles the text-to-speech conversion.
 */
import {ai} from '@/ai/genkit';
import {z} from 'zod';
import wav from 'wav';
import type { Language } from '@/lib/types';

const GenerateAudioInputSchema = z.object({
  text: z.string().describe('The text to convert to speech.'),
  language: z.enum(['english', 'chinese', 'vietnamese']).describe('The language of the text.'),
});
type GenerateAudioInput = z.infer<typeof GenerateAudioInputSchema>;

const GenerateAudioOutputSchema = z.object({
  audioSrc: z.string().describe('The base64 encoded WAV audio data URI.'),
});
type GenerateAudioOutput = z.infer<typeof GenerateAudioOutputSchema>;


export async function generateAudio(input: GenerateAudioInput): Promise<GenerateAudioOutput> {
  return generateAudioFlow(input);
}

// This helper function converts raw PCM audio data from the AI model into a WAV file format (encoded as base64),
// which is required for playback in web browsers.
async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    let bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

const langToVoiceMap: Record<Language, string> = {
    english: 'Algenib', // Supported voice for gemini-2.5-flash-preview-tts
    chinese: 'Deneb',   // Supported voice for gemini-2.5-flash-preview-tts
    vietnamese: 'Fomalhaut', // Supported voice for gemini-2.5-flash-preview-tts
};


const generateAudioFlow = ai.defineFlow(
  {
    name: 'generateAudioFlow',
    inputSchema: GenerateAudioInputSchema,
    outputSchema: GenerateAudioOutputSchema,
  },
  async ({ text, language }) => {
    const voiceName = langToVoiceMap[language] || 'Algenib';

    const { media } = await ai.generate({
      model: 'googleai/gemini-2.5-flash-preview-tts',
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName },
          },
        },
      },
      prompt: text,
    });

    if (!media) {
      throw new Error('No audio media was generated by the model.');
    }

    const audioBuffer = Buffer.from(
      media.url.substring(media.url.indexOf(',') + 1),
      'base64'
    );
    
    const wavBase64 = await toWav(audioBuffer);

    return {
      audioSrc: `data:audio/wav;base64,${wavBase64}`,
    };
  }
);
